# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(480, 742)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 20, 451, 711))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vLayout_main = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vLayout_main.setContentsMargins(0, 0, 0, 0)
        self.vLayout_main.setObjectName("vLayout_main")
        self.vLayout_visor = QtWidgets.QVBoxLayout()
        self.vLayout_visor.setObjectName("vLayout_visor")
        self.title_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.vLayout_visor.addWidget(self.title_label)
        self.graphicsView = QtWidgets.QGraphicsView(self.verticalLayoutWidget)
        self.graphicsView.setObjectName("graphicsView")
        self.vLayout_visor.addWidget(self.graphicsView)
        self.vLayout_main.addLayout(self.vLayout_visor)
        self.vLayout_slider = QtWidgets.QVBoxLayout()
        self.vLayout_slider.setObjectName("vLayout_slider")
        self.hLayout_slider = QtWidgets.QHBoxLayout()
        self.hLayout_slider.setObjectName("hLayout_slider")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.hLayout_slider.addItem(spacerItem)
        self.sliceSlider = QtWidgets.QSlider(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliceSlider.sizePolicy().hasHeightForWidth())
        self.sliceSlider.setSizePolicy(sizePolicy)
        self.sliceSlider.setSliderPosition(50)
        self.sliceSlider.setOrientation(QtCore.Qt.Horizontal)
        self.sliceSlider.setObjectName("sliceSlider")
        self.hLayout_slider.addWidget(self.sliceSlider)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.hLayout_slider.addItem(spacerItem1)
        self.vLayout_slider.addLayout(self.hLayout_slider)
        self.slider_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.slider_label.setFont(font)
        self.slider_label.setAlignment(QtCore.Qt.AlignCenter)
        self.slider_label.setObjectName("slider_label")
        self.vLayout_slider.addWidget(self.slider_label)
        self.vLayout_main.addLayout(self.vLayout_slider)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.vLayout_main.addWidget(self.line)
        self.vLayout_browse = QtWidgets.QVBoxLayout()
        self.vLayout_browse.setContentsMargins(-1, 0, -1, -1)
        self.vLayout_browse.setObjectName("vLayout_browse")
        self.load_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.load_label.setFont(font)
        self.load_label.setAlignment(QtCore.Qt.AlignCenter)
        self.load_label.setObjectName("load_label")
        self.vLayout_browse.addWidget(self.load_label)
        self.hLayout_browse = QtWidgets.QHBoxLayout()
        self.hLayout_browse.setContentsMargins(-1, 0, -1, -1)
        self.hLayout_browse.setObjectName("hLayout_browse")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.hLayout_browse.addItem(spacerItem2)
        self.path_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.path_edit.setInputMask("")
        self.path_edit.setObjectName("path_edit")
        self.hLayout_browse.addWidget(self.path_edit)
        self.browse_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.browse_button.setObjectName("browse_button")
        self.hLayout_browse.addWidget(self.browse_button)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.hLayout_browse.addItem(spacerItem3)
        self.vLayout_browse.addLayout(self.hLayout_browse)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.vLayout_browse.addItem(spacerItem4)
        self.hLayout_loadMRI = QtWidgets.QHBoxLayout()
        self.hLayout_loadMRI.setContentsMargins(-1, 0, -1, -1)
        self.hLayout_loadMRI.setObjectName("hLayout_loadMRI")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.hLayout_loadMRI.addItem(spacerItem5)
        self.loadMRI_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadMRI_button.sizePolicy().hasHeightForWidth())
        self.loadMRI_button.setSizePolicy(sizePolicy)
        self.loadMRI_button.setStyleSheet("border-color: rgb(115, 210, 22);")
        self.loadMRI_button.setObjectName("loadMRI_button")
        self.hLayout_loadMRI.addWidget(self.loadMRI_button)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.hLayout_loadMRI.addItem(spacerItem6)
        self.vLayout_browse.addLayout(self.hLayout_loadMRI)
        spacerItem7 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.vLayout_browse.addItem(spacerItem7)
        self.vLayout_main.addLayout(self.vLayout_browse)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.vLayout_main.addWidget(self.line_3)
        self.vLayout_cb = QtWidgets.QVBoxLayout()
        self.vLayout_cb.setContentsMargins(-1, 0, -1, 0)
        self.vLayout_cb.setObjectName("vLayout_cb")
        self.axis_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.axis_label.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.axis_label.setFont(font)
        self.axis_label.setAlignment(QtCore.Qt.AlignCenter)
        self.axis_label.setObjectName("axis_label")
        self.vLayout_cb.addWidget(self.axis_label)
        self.hLayout_cb = QtWidgets.QHBoxLayout()
        self.hLayout_cb.setContentsMargins(-1, -1, -1, 0)
        self.hLayout_cb.setObjectName("hLayout_cb")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.hLayout_cb.addItem(spacerItem8)
        self.axial_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.axial_cb.setObjectName("axial_cb")
        self.hLayout_cb.addWidget(self.axial_cb)
        self.coronal_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.coronal_cb.setEnabled(True)
        self.coronal_cb.setObjectName("coronal_cb")
        self.hLayout_cb.addWidget(self.coronal_cb)
        self.sagital_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.sagital_cb.setEnabled(True)
        self.sagital_cb.setObjectName("sagital_cb")
        self.hLayout_cb.addWidget(self.sagital_cb)
        self.vLayout_cb.addLayout(self.hLayout_cb)
        spacerItem9 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.vLayout_cb.addItem(spacerItem9)
        self.vLayout_main.addLayout(self.vLayout_cb)
        self.line_4 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.vLayout_main.addWidget(self.line_4)
        self.vLayout_manual = QtWidgets.QVBoxLayout()
        self.vLayout_manual.setContentsMargins(-1, 0, -1, -1)
        self.vLayout_manual.setObjectName("vLayout_manual")
        self.selectSlice_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.selectSlice_label.setFont(font)
        self.selectSlice_label.setAlignment(QtCore.Qt.AlignCenter)
        self.selectSlice_label.setObjectName("selectSlice_label")
        self.vLayout_manual.addWidget(self.selectSlice_label)
        self.hLayout_manual = QtWidgets.QHBoxLayout()
        self.hLayout_manual.setContentsMargins(-1, 0, -1, -1)
        self.hLayout_manual.setObjectName("hLayout_manual")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.hLayout_manual.addItem(spacerItem10)
        self.lineEdit_slice = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_slice.setObjectName("lineEdit_slice")
        self.hLayout_manual.addWidget(self.lineEdit_slice)
        self.loadSlice_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.loadSlice_button.setObjectName("loadSlice_button")
        self.hLayout_manual.addWidget(self.loadSlice_button)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.hLayout_manual.addItem(spacerItem11)
        self.vLayout_manual.addLayout(self.hLayout_manual)
        spacerItem12 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.vLayout_manual.addItem(spacerItem12)
        self.vLayout_main.addLayout(self.vLayout_manual)
        self.line_5 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.vLayout_main.addWidget(self.line_5)
        self.hLayout_foot = QtWidgets.QHBoxLayout()
        self.hLayout_foot.setContentsMargins(-1, 0, -1, -1)
        self.hLayout_foot.setObjectName("hLayout_foot")
        self.footTitle_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.footTitle_label.setFont(font)
        self.footTitle_label.setAlignment(QtCore.Qt.AlignCenter)
        self.footTitle_label.setWordWrap(False)
        self.footTitle_label.setObjectName("footTitle_label")
        self.hLayout_foot.addWidget(self.footTitle_label)
        self.icon_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.icon_label.setText("")
        self.icon_label.setPixmap(QtGui.QPixmap(":/main/img/new_itm_logo_rec_small.png"))
        self.icon_label.setScaledContents(False)
        self.icon_label.setAlignment(QtCore.Qt.AlignCenter)
        self.icon_label.setObjectName("icon_label")
        self.hLayout_foot.addWidget(self.icon_label)
        self.vLayout_main.addLayout(self.hLayout_foot)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "ITM - Visualizador de MRI"))
        self.title_label.setText(_translate("Form", "Visor MRI"))
        self.slider_label.setText(_translate("Form", "<-- Slider -->"))
        self.load_label.setText(_translate("Form", "Load volume"))
        self.path_edit.setPlaceholderText(_translate("Form", "Type path to MRI..."))
        self.browse_button.setText(_translate("Form", "Browse"))
        self.loadMRI_button.setText(_translate("Form", "Load MRI"))
        self.axis_label.setText(_translate("Form", "Select view axis"))
        self.axial_cb.setText(_translate("Form", "Axial"))
        self.coronal_cb.setText(_translate("Form", "Coronal"))
        self.sagital_cb.setText(_translate("Form", "Sagital"))
        self.selectSlice_label.setText(_translate("Form", "Select slice"))
        self.lineEdit_slice.setPlaceholderText(_translate("Form", "Type custom slice number..."))
        self.loadSlice_button.setText(_translate("Form", "Load"))
        self.footTitle_label.setText(_translate("Form", "ITM NIfTI MRI Visualizer"))
import resources_rc
