# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(480, 716)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 20, 451, 681))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vLayout_main = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vLayout_main.setContentsMargins(0, 0, 0, 0)
        self.vLayout_main.setObjectName("vLayout_main")
        self.vLayout_visor = QtWidgets.QVBoxLayout()
        self.vLayout_visor.setObjectName("vLayout_visor")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.vLayout_visor.addWidget(self.label)
        self.graphicsView = QtWidgets.QGraphicsView(self.verticalLayoutWidget)
        self.graphicsView.setObjectName("graphicsView")
        self.vLayout_visor.addWidget(self.graphicsView)
        self.vLayout_main.addLayout(self.vLayout_visor)
        self.vLayout_slider = QtWidgets.QVBoxLayout()
        self.vLayout_slider.setObjectName("vLayout_slider")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalSlider = QtWidgets.QSlider(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        self.horizontalSlider.setSliderPosition(50)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout.addWidget(self.horizontalSlider)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.vLayout_slider.addLayout(self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.vLayout_slider.addWidget(self.label_2)
        self.vLayout_main.addLayout(self.vLayout_slider)
        self.vLayout_load = QtWidgets.QVBoxLayout()
        self.vLayout_load.setContentsMargins(-1, 12, -1, -1)
        self.vLayout_load.setObjectName("vLayout_load")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.vLayout_load.addWidget(self.label_4)
        self.hLayout_load = QtWidgets.QHBoxLayout()
        self.hLayout_load.setContentsMargins(-1, 0, -1, -1)
        self.hLayout_load.setObjectName("hLayout_load")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.hLayout_load.addItem(spacerItem2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.hLayout_load.addWidget(self.lineEdit_2)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.hLayout_load.addWidget(self.pushButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.hLayout_load.addItem(spacerItem3)
        self.vLayout_load.addLayout(self.hLayout_load)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.vLayout_load.addItem(spacerItem4)
        self.vLayout_main.addLayout(self.vLayout_load)
        self.vLayout_cb = QtWidgets.QVBoxLayout()
        self.vLayout_cb.setContentsMargins(-1, 0, -1, 0)
        self.vLayout_cb.setObjectName("vLayout_cb")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.vLayout_cb.addWidget(self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.checkBox_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_2.addWidget(self.checkBox_3)
        self.checkBox_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_2.addWidget(self.checkBox_2)
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.vLayout_cb.addLayout(self.horizontalLayout_2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.vLayout_cb.addItem(spacerItem6)
        self.vLayout_main.addLayout(self.vLayout_cb)
        self.vLayout_manual = QtWidgets.QVBoxLayout()
        self.vLayout_manual.setContentsMargins(-1, 0, -1, -1)
        self.vLayout_manual.setObjectName("vLayout_manual")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.vLayout_manual.addWidget(self.label_7)
        self.hLayout_manual = QtWidgets.QHBoxLayout()
        self.hLayout_manual.setContentsMargins(-1, 0, -1, -1)
        self.hLayout_manual.setObjectName("hLayout_manual")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.hLayout_manual.addItem(spacerItem7)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.hLayout_manual.addWidget(self.lineEdit)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.hLayout_manual.addWidget(self.pushButton_2)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.hLayout_manual.addItem(spacerItem8)
        self.vLayout_manual.addLayout(self.hLayout_manual)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.vLayout_manual.addItem(spacerItem9)
        self.vLayout_main.addLayout(self.vLayout_manual)
        self.hLayout_foot = QtWidgets.QHBoxLayout()
        self.hLayout_foot.setContentsMargins(-1, 0, -1, -1)
        self.hLayout_foot.setObjectName("hLayout_foot")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName("label_6")
        self.hLayout_foot.addWidget(self.label_6)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/main/img/new_itm_logo_rec_small.png"))
        self.label_5.setScaledContents(False)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.hLayout_foot.addWidget(self.label_5)
        self.vLayout_main.addLayout(self.hLayout_foot)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Visor MRI"))
        self.label_2.setText(_translate("Form", "<-- Slider -->"))
        self.label_4.setText(_translate("Form", "Load volume"))
        self.pushButton.setText(_translate("Form", "Browse"))
        self.label_3.setText(_translate("Form", "Axis"))
        self.checkBox_3.setText(_translate("Form", "Axial"))
        self.checkBox_2.setText(_translate("Form", "Coronal"))
        self.checkBox.setText(_translate("Form", "Sagital"))
        self.label_7.setText(_translate("Form", "Select slice"))
        self.pushButton_2.setText(_translate("Form", "Load"))
        self.label_6.setText(_translate("Form", "ITM Nifti MRI Visualizer"))
import resources_rc
